# Общие параметры запуска
web_server:
  address: 127.0.0.1
  port: 8081
  cert_path: "/path/to/cert.pem"
  key_path: "/path/to/key.pem"

# Параметры для REST API хранилища
rest_api_checkpoint:
  base_url: https://api.example.com
  list_name: "Test"